name: Build Push Changes
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build DpResolver
        run: |
          chmod +x gradlew
          ./gradlew :main:jar

      - uses: actions/upload-artifact@v2
        with:
          name: DpResolver
          path: main/build/libs/*.jar